export const inDifferentLanguages = [
  "Happy birthday",
  "Feliz cumpleaños",
  "Joyeux anniversaire",
  "Herzlichen Glückwunsch zum Geburtstag",
  "Buon compleanno",
  "Feliz aniversário",
  "生日快乐",
  "عيد ميلاد سعيد",
  "お誕生日おめでとうございます",
  "생일 축하합니다",
  "Gefeliciteerd met je verjaardag",
  "जन्मदिन की शुभकामनाएं",
  "জন্মদিনের শুভেচ্ছা",
  "Χρόνια Πολλά",
  "Doğum günün kutlu olsun",
  "สุขสันต์วันเกิด",
  "Selamat ulang tahun",
  "Wszystkiego najlepszego z okazji urodzin",
  "Tillykke med fødselsdagen",
  "Grattis på födelsedagen",
  "Gratulerer med dagen",
  "Hyvää syntymäpäivää",
  "Selamat ulang tahun",
  "Boldog születésnapot",
  "Všechno nejlepší k narozeninám",
  "Všetko najlepšie k narodeninám",
  "Sretan rođendan",
  "Srecan rodjendan",
  "Vse najboljše ob rojstnem dnevu",
  "La multi ani",
  "Честит рожден ден",
  "Sveikinu su gimtadieniu",
  "Daudz laimes dzimšanas dienā",
  "Palju õnne sünnipäevaks",
  "Til hamingju með afmæli",
  "زادے کی شاندار تعطیلات",
  "تولدت مبارک",
  "Maligayang kaarawan",
  "Chúc mừng sinh nhật",
  "Maligayang kaarawan",
  "जन्मदिनको शुभकामना",
  "ਜਨਮਦਿਨ ਦਾ ਹੁਣਾਂ ਬਧਾ ਸ਼ੁਭ ਕਾਮਨਾ",
  "जन्मदिनाच्या हार्दिक शुभेच्छा",
  "જન્મદિવસના શુભેચ્છા",
  "பிறந்தநாள் வாழ்த்துக்கள்",
  "జన్మదినాశుభాకాంక్షలు",
  "ಜನ್ಮದಿನ ಶುಭಾಶಯಗಳು",
  "ജന്മദിനാശംസകൾ",
  "උපන් දිනයේ ස්තුතියි",
];
